### ISSUE TITLE
wire binds not updating

### ISSUE THREAD

**Issue by pk-021** [EV-OD/Digital-Logic#10]
For the wires from outputs to the global outputs, the binds are not updating, and it stays the same as it was initialized. This is causing problems in hover detection and drawing of the wires and may lead to unexpected bugs.

**Comment by EV-OD** [comment]
thank you for commenting out

**Comment by pk-021** [comment]
This issue is fixed in the #11 pull  request. The details can be found in the respective pull's comments and descriptions.
