### ISSUE TITLE
segmentation fault when deleting chip

### ISSUE THREAD

**Issue by EV-OD** [EV-OD/Digital-Logic#13]
I designed a circuit ( circuit image is given below).
![image](https://github.com/user-attachments/assets/ea9ee842-9c70-428e-9486-9954485ff434)
I deleted two wires from global input pin to AND input pins.
![image](https://github.com/user-attachments/assets/78a5d076-d5c6-4368-accc-f6516942659f)
After that when I delete chip it gives segmentation fault.

**Comment by pk-021** [comment]
This issue is now fixed in #14.  More details in the pull request.

**Comment by EV-OD** [comment]
thank you for PR
