### ISSUE TITLE
Simultaneous Wire Creation and Chip Dragging Causes Unexpected Behavior

### ISSUE THREAD

**Issue by EV-OD** [EV-OD/Digital-Logic#20]
## Bug Report: Simultaneous Wire Creation and Chip Dragging Causes Unexpected Behavior

**Description:**
When attempting to create a wire from chip pins, if the chip can also be dragged, both events can be triggered simultaneously. This results in both creating a new wire and dragging the chip at the same time.

**Steps to Reproduce:**
1. Attempt to create a wire from a chip pin.
2. While attempting to create the wire, accidentally drag the chip.

**Expected Behavior:**
- Creating a wire should not trigger the chip dragging event simultaneously.
- The wire creation process should be distinct and not interfere with chip dragging actions.

**Actual Behavior:**
- When trying to create a wire, dragging the chip can also occur, leading to the unintended creation of a wire and the chip being moved.

**Environment:**
- **OS:**  win 11

**Additional Context:**
This issue affects the usability and accuracy of wire creation and chip manipulation. It can lead to confusion and errors in circuit design and layout.

**Screenshots or Videos:**
![image](https://github.com/user-attachments/assets/a3b60ce3-7f11-49dd-bbf9-e4b64f83ac4d)

**Possible Solutions:**
- Implement separate event handling for wire creation and chip dragging to prevent simultaneous triggering.
- Add a delay or gesture recognition to distinguish between wire creation and chip dragging actions.

**Development Notes:**
- Ensure that the solution maintains intuitive user interaction without compromising functionality.
- Test the fix across different scenarios and user workflows to validate effectiveness.

**Comment by pk-021** [comment]
This issue is fixed in #25. Further details in #24 and #25.

# solution:

Checked whether the chip is clicked before it is dragged. The drag signal was being generated by GTK before the click signal. So, to counteract the bugs, the ```onMyLeftClick``` function was moved to inside the ```on_my_drag_begin ``` since it is called when the left button is clicked at the beginning of a drag.

**Comment by EV-OD** [comment]
awesome solution
