### ISSUE TITLE
Inconsistent Wire Hover Effect

### ISSUE THREAD

**Issue by EV-OD** [EV-OD/Digital-Logic#23]
## Bug Report: Inconsistent Wire Hover Effect

**Description:**
Sometimes, a wire in the application shows the hover effect even when the mouse cursor is not actually hovering over the wire itself.

**Steps to Reproduce:**
1. Open the application and create a wire between two points.
2. Move the mouse cursor around the vicinity of the wire, but not directly over it.
3. Observe the wire to see if the hover effect appears unexpectedly.

**Expected Behavior:**
- The hover effect should only appear when the mouse cursor is directly over the wire.
- There should be no hover effect when the mouse cursor is nearby but not on the wire.

**Actual Behavior:**
- The wire intermittently displays the hover effect even when the mouse cursor is not directly hovering over it.

**Environment:**
- **OS:** Win 11

**Additional Context:**
This issue affects the visual clarity and user experience when interacting with wires in the application. It can lead to confusion about the state of wire selections or actions.

**Screenshots or Videos:**
![image](https://github.com/user-attachments/assets/d1b03fbb-bd8c-4619-9a5b-db971b8e3d19)

https://github.com/user-attachments/assets/84b1aae0-24d8-430e-ba33-30f43f6e949e

**Possible Solutions:**
- Review and adjust the mouse event handling logic to accurately detect hover states.
- Ensure that the hover effect is triggered only when the mouse cursor is directly over the wire.

**Development Notes:**
- Test the fix thoroughly across different wire configurations and user interactions.
- Consider performance implications of any changes made to the hover effect detection mechanism.

**Comment by pk-021** [comment]
#24 fixes this issue.

# solution:

The ```isHoveringWIre``` function was updated to account for vertical lines and horizontal lines and checks were added for when the mouse is within the segment with proper handling of edge cases.

**Comment by EV-OD** [comment]
thanks
